### ISSUE TITLE
Please add support for student hub

### ISSUE THREAD

**Issue by albeartoz** [kj800x/nulinks#84]

**Comment by kj800x** [comment]
@albeartoz PR #85 should add this. Wanna take a look and see if those changes look good? Let me know and then I'll merge it and push out a deploy for you.

Also, I graduated earlier this year so I'm a bit out of the loop. Let me know if there's any other sites I'm missing!

**Comment by albeartoz** [comment]
Yeah, that’s perfect!

Albert Zhang
